### ISSUE TITLE
Fix spearjump in Knights.c4f/Camp.c4s

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/content#2]
You can easily get into the foregin camp with jumping while throwing a spear. In the default configuration it shouldn't be possible.

**Comment by maxmitti** [comment]
The default can't be changed without destroying many techniques and also some scenarios.
Maybe it should just be a rule.

**Comment by Somebodyisnobody** [comment]
What's about moving the guarding tower a bit higher?

**Comment by maxmitti** [comment]
Yes, why don't you make a Camp-Mod?
I don't want to change this "officially" because I'm sure there are plenty of players who don't want this to be changed.
