### ISSUE TITLE
Add Hazard.c4d

### ISSUE THREAD

**Issue by Somebodyisnobody** [legacyclonk/content#4]
Refering to the discord communication we have the go from 4 of 5 developers of the Hazard-Pack to implement Hazard into LC while they're ok with updating thier CC 3.0 license to a compatible CC-BY-NC 4.0.
This issue is to log the steps we've already tried to contact the last developer "Raven".

- [x] Search desc-files for E-Mail addresses: https://ccan.de/cgi-bin/ccan/ccan-view.pl?f1=ai&m1=e&v1=834
- [ ] Search industrial mechanics with name "Tobias Schuster" (http://ccfmirror.striver.net/ccf.striver.net/userdf6c.html?usr=95)
  - https://github.com/TS-Tobias
- [X] Ask the CCAN-Admins to send a e-mail to the user "Raven" describing the situation

**Comment by Somebodyisnobody** [comment]
E-Mail was sent by arneb on 20211026 without any response until now.

**Comment by Somebodyisnobody** [comment]
I found two additional accounts matching Tobias' e-mail address (found in desc-files)
https://www.youtube.com/user/Tobi7887
https://www.reddit.com/user/tobi7887/

**Comment by Somebodyisnobody** [comment]
Comments on ccan.de have no new information

**Comment by Fulgen301** [comment]
See #5.
